# Generated by Django 4.0.4 on 2022-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_openhours_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='slot_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='slot_start',
            field=models.TimeField(),
        ),
    ]
